version: "3.8"
services:
    bot:
        # Универсальный образ для x86/ARM64
        build: .
        restart: "always"
        stop_signal: SIGINT
        env_file:
            -   .env
#        volumes:
#            # Путь к .env файлу с настройками
#            - "/home/user/casino-bot-redis/.env:/app/.env"
        depends_on:
            - redis
    redis:
        image: redis:7
        restart: "always"
        volumes:
            # Путь к каталогу с redis.conf
            - "./redis/config:/usr/local/etc/redis"
            # Путь к каталогу, где будет лежать дамп базы Redis
            - "./redis/data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
