version: "3.8"
services:
    bot:
        # Универсальный образ для x86/ARM64
        build: ./bot
        restart: "always"
        stop_signal: SIGINT
        env_file:
            - bot/.env
        volumes:
            - "./db:/app/db"
        depends_on:
            - redis
    redis:
        image: redis:7
        restart: "always"
        volumes:
            # Путь к каталогу с redis.conf
            - "./redis/config:/usr/local/etc/redis"
            # Путь к каталогу, где будет лежать дамп базы Redis
            - "./redis/data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
