version: "3.3"
services:
    bot:
        # Универсальный образ для x86/ARM64
        build: ./bot
        restart: "always"
        stop_signal: SIGINT
        env_file:
            - bot/.env
        volumes:
            - "./db:/app/db"
        ports:
            - "8080:8080"
